<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Utilities\**" />
		<Content Remove="Utilities\**" />
		<EmbeddedResource Remove="Utilities\**" />
		<None Remove="Utilities\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Newtonsoft.Json" /> 
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Asp.Versioning.Http" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="Bogus" />
		<PackageReference Include="BuzlinkRepository" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />

		<PackageReference Include="AutoMapper" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="RabbitMQ.Client" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />
 

	</ItemGroup>


</Project>
