<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Hrms.Infrastructure</RootNamespace>
        <UserSecretsId>b37ddffc-25a7-4a18-9b0a-a7576a2570c1</UserSecretsId>
    </PropertyGroup>
    <ItemGroup>
      <Content Include="db\migrations\**\*.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="BuzlinkRepository" />
        <PackageReference Include="Evolve" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql.NetTopologySuite" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
        <PackageReference Include="Serilog.Sinks.Grafana.Loki" />
        <PackageReference Include="System.Management" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\hrms.Domain\hrms.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="db\migrations\" />
    </ItemGroup>
</Project>