services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - hrmsnet
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 60s

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   restart: always
  #   ports:
  #     - "5672:5672"   
  #     - "15672:15672"  
  #   networks:
  #     - hrmsnet
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "check_running"]
  #     interval: 15s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 30s

  api:
    image: jhoncee2018/hrms-api:latest
    container_name: hrms-api
    restart: always
    ports:
      - "8081:8080"
    networks:
      - hrmsnet
    env_file:
      - .env 
    depends_on:
      mysql:
        condition: service_healthy
      # rabbitmq:
      #   condition: service_healthy

networks:
  hrmsnet:
    driver: bridge

volumes:
  mysql_data:
