services:
  hrms-api:
    build:
      context: .
      target: hrms-service
      dockerfile: Dockerfile
    image: jhoncee2018/hrms-api:latest
    container_name: hrms-api
    restart: always
    ports:
      - "8082:8080"
    networks:
      - hrmsnet
    env_file:
      - .env
    volumes:
      - ./data-protection-keys:/app/dp-keys

  adms-api:
    build:
      context: .
      target: adms-service
      dockerfile: Dockerfile
    image: jhoncee2018/hrms-adms-api:latest
    container_name: adms-api
    restart: always
    ports:
      - "8086:8080"
    networks:
      - hrmsnet
    env_file:
      - .env
    volumes:
      - ./data-protection-keys:/app/dp-keys

  # --- NEW: Migration Runner Service ---
  migration-service:
    image: jhoncee2018/hrms-migration:latest
    container_name: hrms-migration-runner
    # No "restart: always" here because this is a short-lived task, not a background daemon
    networks:
      - hrmsnet
    env_file:
      - .env
    environment:
      - ConnectionStrings__TenantStoreConnection=${ConnectionStrings__TenantStoreConnection}

networks:
  hrmsnet:
    external: true
    name: root_hrmsnet
