services: 
  hrms-api:
    build:
      context: .
      target: hrms-service
      dockerfile: Dockerfile
    image: jhoncee2018/hrms-api:latest
    container_name: hrms-api
    restart: always
    ports:
      - "8082:8080"
    networks:
      - hrmsnet
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started          
  adms-api:
    build:
      context: .
      target: adms-service  
      dockerfile: Dockerfile
    image: jhoncee2018/hrms-adms-api:latest
    container_name: adms-api
    restart: always
    ports:
      - "8086:8080"
    networks:
      - hrmsnet
    env_file:
      - .env 
    depends_on:
      mysql:
        condition: service_healthy

networks:
  hrmsnet:
    external: true
    name: root_hrmsnet 