<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>Hrms.Domain</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="BuzlinkRepository" />
		<PackageReference Include="MessagePack" /> 
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\tenantstore\TenantStore\Onepunch.Common.Lib\Onepunch.Common.Lib.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Attibutes\" />
	</ItemGroup>
</Project>