<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>Hrms.Domain</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="BuzlinkRepository" />
		<PackageReference Include="MessagePack" /> 
	</ItemGroup>
</Project>