<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>Hrms.Domain</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Attibutes\**" />
	  <EmbeddedResource Remove="Attibutes\**" />
	  <None Remove="Attibutes\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="BuzlinkRepository" />
		<PackageReference Include="MessagePack" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql.NetTopologySuite" /> 
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\tenantstore\TenantStore\Onepunch.Common.Lib\Onepunch.Common.Lib.csproj" />
	</ItemGroup>
</Project>