<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>DTR.Core</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Messaging\**" />
	  <EmbeddedResource Remove="Messaging\**" />
	  <None Remove="Messaging\**" /> 
	</ItemGroup> 
	<ItemGroup> 
		<PackageReference Include="Polly" />
		<PackageReference Include="MessagePack" />
		<PackageReference Include="Refit.HttpClientFactory" />
		<PackageReference Include="BuzlinkRepository" />
		<PackageReference Include="ExcelMapper" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.AspNetCore" />
		<PackageReference Include="Grpc.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />


		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="System.Management" />
		<PackageReference Include="Confluent.Kafka" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />
	
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Hrms.Core\Hrms.Core.csproj" />
	  <ProjectReference Include="..\..\hrms.Domain\hrms.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>DTR.Core.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
</Project>
