<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x86;x64</Platforms>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>DTR.Models</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Extensions\**" />
	  <EmbeddedResource Remove="Extensions\**" />
	  <None Remove="Extensions\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BuzlinkRepository" />
		<PackageReference Include="MessagePack" />
	</ItemGroup>

</Project>
