<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting"  />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="MassTransit.RabbitMQ"  />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational"   />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools"  />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\tenantstore\TenantStore\Onepunch.Common.Lib\Onepunch.Common.Lib.csproj" />
		<ProjectReference Include="..\tenantstore\TenantStore\TenantStoreApi.Infrastructure\TenantStoreApi.Infrastructure.csproj" />
	</ItemGroup>
</Project>