// <auto-generated />
using System;
using Adms.api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adms.api.Migrations
{
    [DbContext(typeof(AdmsContext))]
    partial class AdmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Adms.api.Domain.Entties.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Verifycode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("WorkDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Workstate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09da0f2d-e5de-43cb-a3cc-2de8e06e8c49"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 3, 22, 5, 44, 56, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("eafaba07-33ae-4ded-aa7b-1adb274d54dc"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 7, 24, 5, 14, 56, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("b6f3b4a3-61b3-4d78-8792-4d72d2c01bc8"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 12, 19, 18, 57, 40, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("6ae557ea-703d-41ee-ad15-f3aaa97260a1"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 11, 24, 17, 53, 17, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("fa0f0948-f426-401d-a017-15bd976d15e5"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 12, 17, 18, 12, 18, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("cdb2dc7d-d1b1-4494-9afb-1dd95efb2116"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 4, 25, 17, 23, 16, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("952ed55c-8312-444a-aced-9960597f7fdf"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 12, 21, 18, 3, 25, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("71f2fce5-05dd-46af-bcbb-f39521ac2fa3"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 7, 31, 18, 22, 49, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("b2f7371c-747f-4435-b5f2-ae76779bbdeb"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 8, 10, 5, 0, 2, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        },
                        new
                        {
                            Id = new Guid("3a2ab99e-602d-46b9-8554-809bc8f0bbdb"),
                            BatchCode = "",
                            BioId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeviceName = "",
                            IP = "127.0.0.1",
                            SN = "",
                            Status = "Active",
                            TenantId = new Guid("f2a115bb-c35f-48d7-b42a-0d5dc5f181a4"),
                            Verifycode = "",
                            WorkDateTime = new DateTime(2025, 11, 14, 5, 12, 47, 0, DateTimeKind.Unspecified),
                            Workstate = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
