using Hrms.Api.Documents.Bir;
using Hrms.Api.Documents.Shared;
using Hrms.Domain.Entities;
using Hrms.Domain.ValueObjects;

namespace Hrms.Api.Documents;

// BIR Form 2316 — Certificate of Compensation Payment/Tax Withheld. Per-employee, per-year,
// always printed (there is no electronic submission format for this the way SSS/PhilHealth/
// Pag-IBIG have — 2316 is issued directly to the employee), so it's generated by stamping the
// computed values onto the actual official template (wwwroot/Bir/2316Sep2021ENCS_Final.pdf)
// rather than drawing a from-scratch replica — see Bir2316FieldMap and PdfOverlayEngine.
public class Bir2316OverlayDocument
{
    private readonly Bir2316Model _data;
    private readonly Company? _company;
    private readonly string _webRootPath;

    public Bir2316OverlayDocument(Bir2316Model data, Company? company, string webRootPath)
    {
        _data = data;
        _company = company;
        _webRootPath = webRootPath;
    }

    // debug=true draws calibration crosshairs/labels alongside the real values — gate this to
    // Development in the controller, never expose it in production.
    public byte[] Generate(bool debug = false)
    {
        var templatePath = Path.Combine(_webRootPath, "Bir", "2316Sep2021ENCS_Final.pdf");
        return PdfOverlayEngine.Render(templatePath, Bir2316FieldMap.Fields, BuildValues(), debug);
    }

    private Dictionary<string, string?> BuildValues() => new()
    {
        ["Year"] = _data.Year.ToString(),

        // EmployeeNo and CivilStatus have no matching box on the real form (see Bir2316FieldMap)
        // -- left out of the map, but still available on Bir2316Model for other uses.
        ["Employee.FullName"] = _data.FullName,
        ["Employee.TIN"] = _data.TIN,
        ["Employee.RDOCode"] = _data.RDOCode,
        ["Employee.Address"] = _data.Address,

        // Employer.RDOCode has no matching box in Part II either -- left out of the map.
        ["Employer.RegisteredName"] = ReportDocumentStyle.CompanyName(_company),
        ["Employer.TIN"] = _company?.TIN,
        ["Employer.Address"] = _company?.Address,

        ["GrossCompensation"] = ReportDocumentStyle.Money(_data.GrossCompensation),
        ["NonTaxableCompensation"] = ReportDocumentStyle.Money(_data.NonTaxableCompensation),
        ["ThirteenthMonthPay"] = ReportDocumentStyle.Money(_data.ThirteenthMonthPay),
        ["TaxableCompensation"] = ReportDocumentStyle.Money(_data.TaxableCompensation),
        // The real form has one combined box for "SSS, GSIS, PHIC, HDMF Mandatory
        // Contributions & Union Dues" (row 36) -- not three separate ones.
        ["GovtContributions"] = ReportDocumentStyle.Money(_data.TotalSSS + _data.TotalPhilHealth + _data.TotalPagIbig),
        ["TotalTaxWithheld"] = ReportDocumentStyle.Money(_data.TotalTaxWithheld),

        ["Employer.SignatoryName"] = string.IsNullOrWhiteSpace(_company?.AuthorizedSignatoryName)
            ? null
            : _company.AuthorizedSignatoryName,
        ["Employer.SignatoryTitle"] = string.IsNullOrWhiteSpace(_company?.AuthorizedSignatoryTitle)
            ? null
            : _company.AuthorizedSignatoryTitle,
        ["Employee.SignatureName"] = _data.FullName,
    };
}
