<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <Compile Remove="UI\Config\Goverment\**" />
        <Compile Remove="UI\Config\Holidays\**" />
        <Compile Remove="UI\Config\Leave\**" />
        <Compile Remove="UI\Transactions\Application\**" />
        <Compile Remove="UI\Transactions\BusinessTrip\**" />
        <Compile Remove="UI\Transactions\SalaryAdjustment\**" />
        <EmbeddedResource Remove="UI\Config\Goverment\**" />
        <EmbeddedResource Remove="UI\Config\Holidays\**" />
        <EmbeddedResource Remove="UI\Config\Leave\**" />
        <EmbeddedResource Remove="UI\Transactions\Application\**" />
        <EmbeddedResource Remove="UI\Transactions\BusinessTrip\**" />
        <EmbeddedResource Remove="UI\Transactions\SalaryAdjustment\**" />
        <None Remove="UI\Config\Goverment\**" />
        <None Remove="UI\Config\Holidays\**" />
        <None Remove="UI\Config\Leave\**" />
        <None Remove="UI\Transactions\Application\**" />
        <None Remove="UI\Transactions\BusinessTrip\**" />
        <None Remove="UI\Transactions\SalaryAdjustment\**" />
        <Page Remove="UI\Config\Goverment\**" />
        <Page Remove="UI\Config\Holidays\**" />
        <Page Remove="UI\Config\Leave\**" />
        <Page Remove="UI\Transactions\Application\**" />
        <Page Remove="UI\Transactions\BusinessTrip\**" />
        <Page Remove="UI\Transactions\SalaryAdjustment\**" />
    </ItemGroup>
    <ItemGroup>
      <Compile Remove="UI\Transactions\AllowanceEntryUI.cs" />
      <Compile Remove="UI\Transactions\AllowanceEntryUI.Designer.cs" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Remove="UI\Transactions\AllowanceEntryUI.resx" />
    </ItemGroup>
    <ItemGroup>
      <Compile Include="UI\Config\Goverment\CreateHDMFForm.cs" />
      <Compile Include="UI\Config\Goverment\CreateHDMFForm.Designer.cs" />
      <Compile Include="UI\Config\Goverment\PHICTableSetupUI.cs" />
      <Compile Include="UI\Config\Goverment\PHICTableSetupUI.Designer.cs" />
      <Compile Include="UI\Config\Holidays\CreateHoliday.cs" />
      <Compile Include="UI\Config\Holidays\CreateHoliday.Designer.cs" />
      <Compile Include="UI\Config\Holidays\HolidayMasterRecord.cs" />
      <Compile Include="UI\Config\Holidays\HolidayMasterRecord.Designer.cs" />
      <Compile Include="UI\Config\Leave\CreateLeave.cs" />
      <Compile Include="UI\Config\Leave\CreateLeave.Designer.cs" />
      <Compile Include="UI\Config\Leave\CreateLeaveMaster.cs" />
      <Compile Include="UI\Config\Leave\CreateLeaveMaster.Designer.cs" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="BuzlinkRepository" />
        <PackageReference Include="DevExpress.Win.Design" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Enrichers.Environment" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Serilog.Sinks.Seq" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="people.ico" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="UI\Config\Goverment\CreateHDMFForm.resx" />
      <EmbeddedResource Include="UI\Config\Goverment\PHICTableSetupUI.resx" />
      <EmbeddedResource Include="UI\Config\Holidays\CreateHoliday.resx" />
      <EmbeddedResource Include="UI\Config\Holidays\HolidayMasterRecord.resx" />
      <EmbeddedResource Include="UI\Config\Leave\CreateLeave.resx" />
      <EmbeddedResource Include="UI\Config\Leave\CreateLeaveMaster.resx" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\dtr-app\3rd\approval\Audit\Audit.csproj" />
        <ProjectReference Include="..\..\dtr-app\3rd\approval\Shared.Contracts\Shared.Contracts.csproj" />
        <ProjectReference Include="..\..\dtr-app\3rd\gsopos\Common\AuthUI\AuthUI.csproj" />
        <ProjectReference Include="..\..\dtr-app\3rd\gsopos\Common\Buzlink.Extensions\Buzlink.Extensions.csproj" />
        <ProjectReference Include="..\..\dtr-app\3rd\gsopos\Common\Encryption\Encryption.csproj" />
        <ProjectReference Include="..\Hrms.Core\Hrms.Core.csproj" />
        <ProjectReference Include="..\hrms.Domain\hrms.Domain.csproj" />
        <ProjectReference Include="..\hrms.Infrastructure\hrms.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Compile Update="UI\Config\OtherIncomeCategory.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="UI\Config\OtherIncomeSetupUI.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>
    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>